#!/bin/bash
# Packages the built .app into a distributable, "fancy" installer DMG:
# app icon on the left, an Applications-folder alias in the middle,
# and the setup guide as a visible text file on the right, all at
# 96x96 icon size. The final DMG is compressed/read-only ("locked") -
# not something end users can accidentally modify.
#
# Uses dmgbuild (pip) rather than the classic osascript/Finder-AppleEvent
# approach: writing the .DS_Store layout directly needs no "Automation"
# TCC permission for Finder, which isn't something this script can grant
# itself if denied - and building a DMG headlessly (CI, no active Finder
# session) can't rely on live Finder scripting working at all anyway.
#
# Requires build_app.sh to have been run first (or runs it automatically
# below if the .app isn't there yet).
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/build"
BUNDLE_NAME="ObscuraLux Unwarez.app"
APP_PATH="$BUILD_DIR/$BUNDLE_NAME"

if [ ! -d "$APP_PATH" ]; then
    echo "[*] $BUNDLE_NAME not found - building it first..."
    bash "$SCRIPT_DIR/build_app.sh"
fi

# Version comes from Info.plist (the single source of truth, bumped by
# build_app.sh on every build) rather than a hardcoded copy here, so the
# DMG name can never drift out of sync with the .app it's packaging.
VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$SCRIPT_DIR/Info.plist")
VOLUME_NAME="ObscuraLux Unwarez v${VERSION}"
DMG_NAME="ObscuraLux Unwarez v${VERSION}.dmg"
FINAL_DMG="$BUILD_DIR/$DMG_NAME"
STAGING_DIR="$BUILD_DIR/.dmg_staging"
SETTINGS_FILE="$BUILD_DIR/.dmgbuild_settings.py"

echo "[1/3] Checking for dmgbuild..."
if ! python3 -c "import dmgbuild" >/dev/null 2>&1; then
    echo "dmgbuild not found. Install it with:"
    echo "  pip3 install dmgbuild"
    exit 1
fi

echo "[2/3] Preparing staging folder..."
rm -rf "$STAGING_DIR" "$FINAL_DMG"
mkdir -p "$STAGING_DIR"
sed "s/{{VERSION}}/v${VERSION}/" "$SCRIPT_DIR/dmg_readme.txt" > "$STAGING_DIR/Read Me First.txt"

cat > "$SETTINGS_FILE" <<PYEOF
# Auto-generated by build_dmg.sh - do not edit directly.
app = "${APP_PATH}"
readme = "${STAGING_DIR}/Read Me First.txt"

format = "UDZO"
size = None
files = [app, readme]
symlinks = {"Applications": "/Applications"}

# Left to right: app, Applications alias, setup guide - matches the
# layout used in previous DMG releases.
icon_locations = {
    "${BUNDLE_NAME}": (130, 190),
    "Applications": (330, 190),
    "Read Me First.txt": (530, 190),
}
icon_size = 96
window_rect = ((100, 100), (680, 370))
default_view = "icon-view"
show_status_bar = False
show_tab_view = False
show_pathbar = False
show_sidebar = False
show_toolbar = False
PYEOF

echo "[3/3] Building $DMG_NAME..."
python3 -m dmgbuild -s "$SETTINGS_FILE" "$VOLUME_NAME" "$FINAL_DMG"

rm -rf "$STAGING_DIR" "$SETTINGS_FILE"

echo ""
echo "Built: $FINAL_DMG"
